### ISSUE TITLE
Technical Writing - your questions!

### ISSUE THREAD

**Issue by joenash** [campus-experts/fall-2016#32]
Hey folks,

We're looking ahead at the next talks! One of the suggested topics was technical writing.

What questions do you have about technical writing? This could be documentation, blogging, articles, books, **any** form of writing for technical people or on technical topics. 

Drop your questions below!

**Comment by gillchristian** [comment]
Awesome!!!

- Best practices for writing, not only how the article/post/whatever should look like but also about the process of writing it.
- How to find topics to write about.

**Comment by ruxiang05** [comment]
*How to write about technical topics when you aren't confident about it
*Best practices for writing
*How to get ideas on technical writing

**Comment by kim-codes** [comment]
Hey! Here are some questions I had: 
- How does technical writing differ from any other type of writing ? What should we pay attention to/be mindful of?
- How in-depth do we go? Does it depend on our audience? Is that something we should define before (define our audience)? 
- Is writing in first person for technical writing 'bad'? 
- If it would be possible to see a 'bad' technical post vs a 'good' technical post. 

I might have some more questions later :D

**Comment by shubheksha** [comment]
I've a lot of questions in common with what has been posted already. To add to those:

- How much do you need to know about the topic?
- How do we decide the difficulty level of the post?
- Average amount of research needed for a topic you're not to familiar with/an expert on
- How to choose a title that caters to the majority of the audience w/o evading anyone?

I'll update this as and when I can think of more questions!
Also, would it be possible to get feedback on posts we've written in the past/plan to write in the near future?

**Comment by Lionex** [comment]
I want to better understand how we can reach the audience that exists for technical blog posts and similar writing:

- How do we find or identify an audience?
- What helps to reach a wide audience?

I have some questions on writing to educate or inform an audience:

- How should we approach pedagogical writing, and what kinds of supporting or supplementary materials should we provide?

And finally, some questions on style and mechanics:

- What style, in a literary and grammatical sense, do we employ in technical writing?
- How can we create effective supporting documents?  (I mean items like meeting notes, design specs, etc)
