### ISSUE TITLE
Local Hack Day 2016

### ISSUE THREAD

**Issue by joenash** [campus-experts/fall-2016#33]
3rd December is Local Hack Day! http://localhackday.mlh.io

I'd love to hear which of you are:
a) organising a Local Hack Day 
b) planning to attending one
c) would like to attend one but don't currently have any plans

If there's anything we can do to make any of the above easier, let us know. Especially for **a** and **c**: if you're struggling with the event, or struggling to make it to a nearby event, please drop by for a chat!

GitHub is global sponsor this year, and there will be octo-swag everywhere! This could be a great first opportunity to proudly wave your Campus Expert banners and dive in to help your community. If you're interested in supporting a nearby Local Hack Day as a mentor, comment below or DM me and let's see what we can do 😀

**Comment by joenash** [comment]
@yosufali organising City University, London LHD 🎉 
@sara-h-chen organising Durham LHD 🎈 
@xoneco organising UCL LHD 🎂 

You can find a nearby event here! https://localhackday.mlh.io/find-an-event/

**Comment by gcttong** [comment]
hey we're helping to organize LHD at University of Manitoba, Canada!

**Comment by kim-codes** [comment]
Our organization decided not to host one this year because it is during finals :( 
I'd love to be a mentor however I don't think anyone is organizing one in my city (Montreal, Qc, Canada).

**Comment by joenash** [comment]
@DickensA I guess you'll be at the Nottingham LHD? And @ruxiang05 at KCL? 

@oladushkas are you involved in the Kyiv one? It's at NU Kyiv-Mohyla academy

@shubheksha @hackerkid There's quite a few in India! Might be worth checking if there are any near you! 

@spejss Are you behind the Fachhochschule Dortmund one?

@kim-codes Unfortunately looks like none near Montreal :( If there are any at a distance that you're happy travelling for a day event though, let me know. Why is Canada so big!

**Comment by joenash** [comment]
@avijeets I'm guessing you'll be at Rutgers?

**Comment by joenash** [comment]
@ShiyuL Will you be at the McMaster one?
@gcttong Manitoba is hosting one too! Are you there?

I'm just now realising how many of you may be at or organising a LHD haha!

**Comment by joenash** [comment]
@gcttong Awesome! Have you got everything you need?

**Comment by gcttong** [comment]
@joenash We're trying to get higher numbers, we're at 70 hackers so far (first one ever in Manitoba!) and trying to figure out the following:
1) Prizes (none so far, do we need any?)
2) Wondering how swag works, since we listed we expected 100 hackers, but don't know what happens if we end up getting more participants that the actual number and the site say MLH already sent it out on Nov 14?
3) workshops(working with local hacker space to bring speakers)
4) got any tips on securing hardware? 
Thanks!

**Comment by joenash** [comment]
@gcttong That is loads for a LHD! Great job! 

1) I wouldn't worry about prizes, I actually think the lack of prizes is what makes LHD so great. It's meant to be a chill intro to hackathons for new hackers, and competition could be a bit intimidating at that stage. 
2) MLH will likely have shipped plenty of spares when it comes to stickers etc, however if you exceed 100 it may be a bit scarce on some swag. If this is is a concern, let me know and we'll ship out some GitHub swag to bulk it out :) 
3) Also remember there will be loads of online workshops provided by MLH and sponsors as part of the event! 
4) Local hacker space is a great place to start here, and you're already working with them. Asking more experienced attendees to bring their dev kits and helping new hackers learn how to use them could also be great, as the newbies will not just get the hardware, but a helping hand in using it!

**Comment by joenash** [comment]
@SamOutlan Guessing the Florida Polytechnic one is you? :D

**Comment by SamOutlan** [comment]
@joenash Yes! We're trying to work through an issue with getting food but we're really excited! :D

**Comment by spejss** [comment]
@joenash yes I am behind the one at the Fachhochschule Dortmund :) Sadly, we had to begin promoting it after the deadline for swag has passed.

**Comment by ruxiang05** [comment]
@joenash yeah will be there for KCL LHD! Not organising it myself though

**Comment by PeterDaveHello** [comment]
@joenash I'll like to organize one, and just registered on http://localhackday.mlh.io, now waiting for approval!
